version: "3.8"

services:
  timescaledb:
    image: timescale/timescaledb-postgis:2.1.0-pg13
    restart: always
    ports:
      - ${PG_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}

  hasura:
    image: hasura/graphql-engine:v1.3.3.cli-migrations-v2
    ports:
      - ${HASURA_PORT}:8080
    depends_on:
      - timescaledb
    volumes:
      - "./hasura/metadata:/hasura-metadata"
      - "./hasura/migrations:/hasura-migrations"
    restart: always
    environment:
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
      HASURA_GRAPHQL_DATABASE_URL: postgres://${PG_USERNAME}:${PG_PASSWORD}@timescaledb/${PG_DATABASE}
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log

volumes:
  db_data:
